import { spawn } from 'node:child_process';
import type Database from 'better-sqlite3';
import { normalizeUrl } from '../normalize/url.js';
import { refreshResourceSearchText } from '../resources/searchIndex.js';
import {
  type ExtractionAdapter,
  type ExtractionAdapterContext,
  type ExtractionAdapterResult,
  type ExtractionRequest,
} from './adapterContracts.js';
import { EXTRACTION_RECIPES } from './runtime.js';
import {
  deriveYouTubeQuality,
  YouTubeAdapterPolicy,
  YouTubeMetadataArtifact,
  type YouTubeAdapterPolicy as YouTubeAdapterPolicyValue,
  type YouTubeMetadataArtifact as YouTubeMetadataArtifactValue,
  type YouTubeTranscriptArtifact as YouTubeTranscriptArtifactValue,
} from './youtubeContracts.js';

export const YOUTUBE_MANUAL_TRANSCRIPT_RECIPE = 'youtube_manual_transcript.v1';

export interface ParsedYouTubeUrl {
  videoId?: string;
  playlistId?: string;
  kind: 'youtube_video' | 'youtube_short' | 'youtube_playlist';
  canonicalUrl: string;
}

export interface YouTubeOfficialMetadataFetchOptions {
  apiKey?: string;
  apiBaseUrl?: string;
  fetchImpl?: typeof fetch;
}

export interface YouTubeOfficialMetadataBatchResult {
  status: 'complete' | 'adapter_disabled' | 'failed_network' | 'failed_parse';
  videos: Map<string, YouTubeMetadataArtifactValue>;
  warnings: string[];
}

export interface ManualTranscriptImportInput {
  resourceId: string;
  plainText: string;
  language?: string;
  isAutoGenerated?: boolean;
}

type YouTubeTranscriptSegmentValue = {
  startSeconds: number;
  durationSeconds?: number;
  text: string;
};

export function parseYouTubeUrl(rawUrl: string): ParsedYouTubeUrl | null {
  const n = normalizeUrl(rawUrl);
  if (!n.kind.startsWith('youtube_')) return null;
  const kind = n.kind === 'youtube_playlist' ? 'youtube_playlist' : n.kind === 'youtube_short' ? 'youtube_short' : 'youtube_video';
  return { videoId: n.ids.videoId, playlistId: n.ids.playlistId, kind, canonicalUrl: n.canonicalUrl };
}

export function buildYouTubeMetadataOnlyArtifact(rawUrl: string, title?: string): YouTubeMetadataArtifactValue | null {
  const parsed = parseYouTubeUrl(rawUrl);
  if (!parsed) return null;
  const transcript: YouTubeTranscriptArtifactValue = {
    status: 'not_attempted',
    provenance: 'none',
    segments: [],
  };
  return YouTubeMetadataArtifact.parse({
    videoId: parsed.videoId ?? '',
    playlistId: parsed.playlistId,
    canonicalUrl: parsed.canonicalUrl,
    title,
    transcript,
    extractionQuality: deriveYouTubeQuality({ transcript }),
  });
}

export function createYouTubeOfficialMetadataAdapter(
  policyInput: Partial<YouTubeAdapterPolicyValue> = {},
  fetchOptions: Omit<YouTubeOfficialMetadataFetchOptions, 'apiKey'> = {},
): ExtractionAdapter {
  const policy = YouTubeAdapterPolicy.parse(policyInput);
  return {
    id: 'youtube.official-data-api',
    version: '1.0.0',
    recipeIds: [EXTRACTION_RECIPES.youtubeStandard],
    supports: request => request.urlKind.startsWith('youtube_') && Boolean(parseYouTubeUrl(request.canonicalUrl)?.videoId),
    async run(request) {
      if (!policy.officialDataApi.enabled) return disabledAdapterResult(request, this.id, this.version, 'official Data API disabled');
      const apiKey = process.env[policy.officialDataApi.apiKeyEnvironmentVariable];
      if (!apiKey) return disabledAdapterResult(request, this.id, this.version, 'missing YouTube API key');
      const parsed = parseYouTubeUrl(request.canonicalUrl);
      if (!parsed?.videoId) return notAvailableResult(request, this.id, this.version, 'missing video ID');
      const batch = await fetchYouTubeVideoMetadataBatch([parsed.videoId], { ...fetchOptions, apiKey });
      const metadata = batch.videos.get(parsed.videoId);
      if (batch.status !== 'complete') {
        return { adapterId: this.id, status: batch.status, artifacts: [], warnings: batch.warnings };
      }
      if (!metadata) return notAvailableResult(request, this.id, this.version, 'video not returned by API');
      return metadataResult(request, this.id, this.version, metadata, batch.warnings);
    },
  };
}

export async function fetchYouTubeVideoMetadataBatch(
  videoIds: string[],
  options: YouTubeOfficialMetadataFetchOptions = {},
): Promise<YouTubeOfficialMetadataBatchResult> {
  const ids = [...new Set(videoIds.filter(Boolean))];
  const videos = new Map<string, YouTubeMetadataArtifactValue>();
  if (!options.apiKey) return { status: 'adapter_disabled', videos, warnings: ['missing YouTube API key'] };
  if (!ids.length) return { status: 'complete', videos, warnings: [] };

  const base = options.apiBaseUrl ?? 'https://www.googleapis.com/youtube/v3/videos';
  const url = new URL(base);
  url.searchParams.set('part', 'snippet,contentDetails');
  url.searchParams.set('id', ids.join(','));
  url.searchParams.set('key', options.apiKey);

  try {
    const response = await (options.fetchImpl ?? fetch)(url.toString(), { method: 'GET' });
    if (!response.ok) {
      return { status: 'failed_network', videos, warnings: [`YouTube API returned ${response.status}`] };
    }
    const payload = await response.json() as { items?: unknown[] };
    for (const item of payload.items ?? []) {
      const mapped = mapYouTubeDataApiItem(item);
      if (mapped) videos.set(mapped.videoId, mapped);
    }
    return { status: 'complete', videos, warnings: missingIds(ids, videos) };
  } catch (error) {
    return {
      status: error instanceof SyntaxError ? 'failed_parse' : 'failed_network',
      videos,
      warnings: [error instanceof Error ? error.message : String(error)],
    };
  }
}

export function mapYouTubeDataApiItem(raw: unknown): YouTubeMetadataArtifactValue | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const item = raw as Record<string, unknown>;
  const videoId = typeof item.id === 'string' ? item.id : undefined;
  if (!videoId) return null;
  const snippet = asRecord(item.snippet);
  const contentDetails = asRecord(item.contentDetails);
  const descriptionText = readString(snippet.description);
  const transcript: YouTubeTranscriptArtifactValue = {
    status: 'not_attempted',
    provenance: 'none',
    segments: [],
  };
  return YouTubeMetadataArtifact.parse({
    videoId,
    canonicalUrl: `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`,
    title: readString(snippet.title),
    channelId: readString(snippet.channelId),
    channelTitle: readString(snippet.channelTitle),
    descriptionText,
    durationSeconds: parseIso8601Duration(readString(contentDetails.duration) ?? ''),
    publishedAt: readString(snippet.publishedAt),
    thumbnailUrl: selectThumbnailUrl(asRecord(snippet.thumbnails)),
    tags: readStringArray(snippet.tags),
    chapters: parseChaptersFromDescription(descriptionText ?? ''),
    linksMentioned: extractLinks(descriptionText ?? ''),
    transcript,
    extractionQuality: deriveYouTubeQuality({ descriptionText, transcript }),
  });
}

export function createYouTubeYtDlpAdapter(
  policyInput: Partial<YouTubeAdapterPolicyValue> = {},
  runner: (executable: string, args: string[], context: ExtractionAdapterContext) => Promise<unknown> = runYtDlpJson,
): ExtractionAdapter {
  const policy = YouTubeAdapterPolicy.parse(policyInput);
  return {
    id: 'youtube.local-ytdlp',
    version: '1.0.0',
    recipeIds: [EXTRACTION_RECIPES.youtubeStandard],
    supports: request => request.urlKind.startsWith('youtube_') && Boolean(parseYouTubeUrl(request.canonicalUrl)?.videoId),
    async run(request, context) {
      if (!policy.localYtDlp.enabled) return disabledAdapterResult(request, this.id, this.version, 'local yt-dlp disabled');
      const args = buildYtDlpMetadataArgs(request.canonicalUrl, policy);
      const info = await runner(policy.localYtDlp.executable, args, context);
      const metadata = mapYtDlpMetadata(request, info, policy);
      return metadataResult(request, this.id, this.version, metadata, []);
    },
  };
}

export function buildYtDlpMetadataArgs(url: string, policyInput: Partial<YouTubeAdapterPolicyValue> = {}): string[] {
  const policy = YouTubeAdapterPolicy.parse(policyInput);
  const args = [
    '--dump-single-json',
    '--skip-download',
    '--no-playlist',
    '--write-sub',
    '--sub-langs',
    policy.localYtDlp.preferredLanguages.join(','),
  ];
  if (policy.localYtDlp.allowAutomaticCaptions) args.push('--write-auto-sub');
  args.push(url);
  assertNoMediaDownloadArgs(args);
  return args;
}

export function assertNoMediaDownloadArgs(args: string[]): void {
  const forbidden = new Set(['--extract-audio', '--audio-format', '--recode-video', '--download-sections', '-f', '--format']);
  if (!args.includes('--skip-download')) throw new Error('yt-dlp args must include --skip-download');
  for (const arg of args) {
    if (forbidden.has(arg)) throw new Error(`yt-dlp media download argument is not allowed: ${arg}`);
  }
}

export function mapYtDlpMetadata(
  request: Pick<ExtractionRequest, 'canonicalUrl' | 'title'>,
  raw: unknown,
  policyInput: Partial<YouTubeAdapterPolicyValue> = {},
): YouTubeMetadataArtifactValue {
  const policy = YouTubeAdapterPolicy.parse(policyInput);
  const info = asRecord(raw);
  const videoId = readString(info.id) ?? parseYouTubeUrl(request.canonicalUrl)?.videoId ?? '';
  const descriptionText = readString(info.description);
  const transcript = selectYtDlpTranscript(info, policy);
  return YouTubeMetadataArtifact.parse({
    videoId,
    canonicalUrl: `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`,
    title: readString(info.title) ?? request.title,
    channelId: readString(info.channel_id),
    channelTitle: readString(info.channel),
    descriptionText,
    durationSeconds: typeof info.duration === 'number' ? info.duration : undefined,
    publishedAt: readString(info.upload_date),
    thumbnailUrl: readString(info.thumbnail),
    tags: readStringArray(info.tags),
    chapters: parseChaptersFromDescription(descriptionText ?? ''),
    linksMentioned: extractLinks(descriptionText ?? ''),
    transcript,
    extractionQuality: deriveYouTubeQuality({ descriptionText, transcript }),
  });
}

export function selectYtDlpTranscript(
  info: Record<string, unknown>,
  policyInput: Partial<YouTubeAdapterPolicyValue> = {},
): YouTubeTranscriptArtifactValue {
  const policy = YouTubeAdapterPolicy.parse(policyInput);
  const manual = selectTranscriptFromCollection(asRecord(info.subtitles), false);
  if (manual) return manual;
  if (policy.localYtDlp.allowAutomaticCaptions) {
    const automatic = selectTranscriptFromCollection(asRecord(info.automatic_captions), true);
    if (automatic) return automatic;
  }
  return {
    status: 'not_available',
    provenance: 'optional_local_ytdlp',
    segments: [],
    failureReason: 'No matching subtitle artifact was available.',
  };
}

export function importManualYouTubeTranscript(
  db: Database.Database,
  input: ManualTranscriptImportInput,
): { artifactId: string; transcript: YouTubeTranscriptArtifactValue } {
  const resource = db.prepare(`
    SELECT id, canonical_url, redacted_url, url_kind, title_best
    FROM resources
    WHERE id = ?
  `).get(input.resourceId) as {
    id: string;
    canonical_url: string;
    redacted_url: string;
    url_kind: string;
    title_best: string | null;
  } | undefined;
  if (!resource) throw new Error(`Resource not found: ${input.resourceId}`);
  if (!resource.url_kind.startsWith('youtube_')) throw new Error('Manual YouTube transcript requires a YouTube resource');

  const parsed = parseYouTubeUrl(resource.canonical_url);
  if (!parsed) throw new Error('Invalid YouTube URL');
  const transcript: YouTubeTranscriptArtifactValue = {
    status: 'available_artifact',
    provenance: 'manual_paste',
    language: input.language,
    isAutoGenerated: Boolean(input.isAutoGenerated),
    segments: parseManualTranscriptSegments(input.plainText),
    plainText: normalizeTranscriptText(input.plainText),
  };
  const metadata = YouTubeMetadataArtifact.parse({
    videoId: parsed.videoId ?? '',
    playlistId: parsed.playlistId,
    canonicalUrl: parsed.canonicalUrl,
    title: resource.title_best ?? undefined,
    transcript,
    extractionQuality: deriveYouTubeQuality({ transcript }),
  });
  const artifactId = `art_${resource.id}_${YOUTUBE_MANUAL_TRANSCRIPT_RECIPE.replace(/[^a-z0-9]+/gi, '_')}`;
  db.prepare(`
    INSERT INTO extraction_artifacts
      (id, resource_id, recipe_id, artifact_kind, text_excerpt, json_payload, source_url, provenance, confidence, status, extracted_at)
    VALUES
      (?, ?, ?, 'youtube_manual_transcript', ?, ?, ?, ?, 1, 'complete', ?)
    ON CONFLICT(resource_id, recipe_id) DO UPDATE SET
      artifact_kind = excluded.artifact_kind,
      text_excerpt = excluded.text_excerpt,
      json_payload = excluded.json_payload,
      source_url = excluded.source_url,
      provenance = excluded.provenance,
      confidence = excluded.confidence,
      status = excluded.status,
      error_code = NULL,
      extracted_at = excluded.extracted_at
  `).run(
    artifactId,
    resource.id,
    YOUTUBE_MANUAL_TRANSCRIPT_RECIPE,
    transcript.plainText?.slice(0, 4000) ?? '',
    JSON.stringify(metadata),
    resource.redacted_url,
    JSON.stringify({
      trust: 'user_authored',
      adapterId: 'youtube.manual-transcript',
      adapterVersion: '1.0.0',
      fetchedAt: new Date().toISOString(),
      sourceUrl: resource.redacted_url,
      notes: ['user supplied transcript text'],
    }),
    new Date().toISOString(),
  );
  refreshResourceSearchText(db, resource.id);
  return { artifactId, transcript };
}

export function isDetailedAtomicItemSupportedByEvidence(input: {
  urlKind: string;
  title?: string;
  evidenceRefs: string[];
  evidence: Array<{ id: string; kind: string; text: string; provenance: string }>;
}): boolean {
  if (!input.evidenceRefs.length) return false;
  if (!input.urlKind.startsWith('youtube_')) return true;
  const byId = new Map(input.evidence.map(evidence => [evidence.id, evidence]));
  const refs = input.evidenceRefs.map(ref => byId.get(ref)).filter((item): item is { id: string; kind: string; text: string; provenance: string } => Boolean(item));
  if (refs.some(ref => ref.kind.includes('transcript') || ref.kind.includes('chapter') || ref.kind.includes('description'))) return true;
  if (refs.some(ref => ref.kind.startsWith('youtube_') && ref.text.length > 180)) return true;
  if (input.title && isListLikeTitle(input.title) && refs.length >= 2) return true;
  return false;
}

function metadataResult(
  request: ExtractionRequest,
  adapterId: string,
  adapterVersion: string,
  metadata: YouTubeMetadataArtifactValue,
  warnings: string[],
): ExtractionAdapterResult {
  const status = metadata.extractionQuality === 'metadata_only' ? 'metadata_only' : 'complete';
  return {
    adapterId,
    status,
    warnings,
    artifacts: [{
      resourceId: request.resourceId,
      recipeId: request.recipeId,
      artifactKind: 'youtube_metadata',
      status,
      textExcerpt: youtubeTextExcerpt(metadata),
      jsonPayload: metadata,
      confidence: metadata.transcript.status === 'available_artifact' ? 0.95 : 0.82,
      provenance: {
        trust: adapterId === 'youtube.official-data-api' ? 'official_api' : 'local_adapter',
        adapterId,
        adapterVersion,
        fetchedAt: new Date().toISOString(),
        sourceUrl: request.redactedUrl,
        notes: warnings,
      },
    }],
  };
}

function disabledAdapterResult(
  request: ExtractionRequest,
  adapterId: string,
  adapterVersion: string,
  reason: string,
): ExtractionAdapterResult {
  return {
    adapterId,
    status: 'adapter_disabled',
    warnings: [reason],
    artifacts: [{
      resourceId: request.resourceId,
      recipeId: request.recipeId,
      artifactKind: 'youtube_metadata',
      status: 'adapter_disabled',
      textExcerpt: reason,
      jsonPayload: { transcript: { status: 'adapter_disabled', provenance: 'none', segments: [], failureReason: reason } },
      confidence: 0,
      provenance: {
        trust: 'official_api',
        adapterId,
        adapterVersion,
        fetchedAt: new Date().toISOString(),
        sourceUrl: request.redactedUrl,
        notes: [reason],
      },
    }],
  };
}

function notAvailableResult(
  request: ExtractionRequest,
  adapterId: string,
  adapterVersion: string,
  reason: string,
): ExtractionAdapterResult {
  return {
    adapterId,
    status: 'not_available',
    warnings: [reason],
    artifacts: [{
      resourceId: request.resourceId,
      recipeId: request.recipeId,
      artifactKind: 'youtube_metadata',
      status: 'not_available',
      textExcerpt: reason,
      jsonPayload: buildYouTubeMetadataOnlyArtifact(request.canonicalUrl, request.title) ?? {},
      confidence: 0.2,
      provenance: {
        trust: 'public_metadata',
        adapterId,
        adapterVersion,
        fetchedAt: new Date().toISOString(),
        sourceUrl: request.redactedUrl,
        notes: [reason],
      },
    }],
  };
}

function mapYouTubeDataApiItemThumbnail(thumbnails: Record<string, unknown>, key: string): string | undefined {
  return readString(asRecord(thumbnails[key]).url);
}

function selectThumbnailUrl(thumbnails: Record<string, unknown>): string | undefined {
  return mapYouTubeDataApiItemThumbnail(thumbnails, 'maxres')
    ?? mapYouTubeDataApiItemThumbnail(thumbnails, 'standard')
    ?? mapYouTubeDataApiItemThumbnail(thumbnails, 'high')
    ?? mapYouTubeDataApiItemThumbnail(thumbnails, 'medium')
    ?? mapYouTubeDataApiItemThumbnail(thumbnails, 'default');
}

function youtubeTextExcerpt(metadata: YouTubeMetadataArtifactValue): string {
  return [
    metadata.title,
    metadata.channelTitle ? `channel: ${metadata.channelTitle}` : '',
    metadata.durationSeconds !== undefined ? `duration: ${metadata.durationSeconds}s` : '',
    metadata.descriptionText ? `description: ${metadata.descriptionText.slice(0, 1200)}` : '',
    metadata.chapters.length ? `chapters: ${metadata.chapters.map(chapter => chapter.title).join(', ')}` : '',
    metadata.linksMentioned.length ? `links: ${metadata.linksMentioned.join(' ')}` : '',
    `transcript: ${metadata.transcript.status}`,
    metadata.transcript.plainText ? metadata.transcript.plainText.slice(0, 1600) : '',
  ].filter(Boolean).join(' | ');
}

function parseIso8601Duration(value: string): number | undefined {
  const match = value.match(/^P(?:\d+D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);
  if (!match) return undefined;
  const hours = Number(match[1] ?? 0);
  const minutes = Number(match[2] ?? 0);
  const seconds = Number(match[3] ?? 0);
  return hours * 3600 + minutes * 60 + seconds;
}

export function parseChaptersFromDescription(description: string): Array<{ title: string; startSeconds: number }> {
  return description
    .split(/\r?\n/)
    .flatMap(line => {
      const match = line.match(/^\s*((?:\d{1,2}:)?\d{1,2}:\d{2})\s+(.+?)\s*$/);
      if (!match) return [];
      return [{ startSeconds: parseTimestamp(match[1]), title: match[2] }];
    });
}

export function extractLinks(text: string): string[] {
  const links = new Set<string>();
  for (const match of text.matchAll(/\bhttps?:\/\/[^\s<>)"']+/gi)) {
    try {
      const url = new URL(match[0]);
      url.hash = '';
      links.add(url.toString());
    } catch {
      // Ignore malformed links in creator descriptions.
    }
  }
  return [...links];
}

function selectTranscriptFromCollection(collection: Record<string, unknown>, isAutoGenerated: boolean): YouTubeTranscriptArtifactValue | null {
  for (const [language, value] of Object.entries(collection)) {
    const candidates = Array.isArray(value) ? value : [value];
    for (const candidate of candidates) {
      const record = asRecord(candidate);
      const segments = readSegments(record.segments);
      const plainText = normalizeTranscriptText(readString(record.data) ?? readString(record.text) ?? segments.map(segment => segment.text).join(' '));
      if (!plainText) continue;
      return {
        status: 'available_artifact',
        provenance: 'optional_local_ytdlp',
        language,
        isAutoGenerated,
        segments,
        plainText,
      };
    }
  }
  return null;
}

function readSegments(value: unknown): YouTubeTranscriptSegmentValue[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap(segment => {
    const record = asRecord(segment);
    const text = readString(record.text);
    const startSeconds = typeof record.start === 'number' ? record.start : typeof record.startSeconds === 'number' ? record.startSeconds : undefined;
    if (!text || startSeconds === undefined) return [];
    const durationSeconds = typeof record.duration === 'number' ? record.duration : typeof record.durationSeconds === 'number' ? record.durationSeconds : undefined;
    return [{ startSeconds, durationSeconds, text }];
  });
}

function parseManualTranscriptSegments(text: string): YouTubeTranscriptSegmentValue[] {
  const normalized = normalizeTranscriptText(text);
  return normalized ? [{ startSeconds: 0, text: normalized }] : [];
}

function normalizeTranscriptText(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function parseTimestamp(value: string): number {
  return value.split(':').map(Number).reduce((total, part) => total * 60 + part, 0);
}

function missingIds(ids: string[], videos: Map<string, YouTubeMetadataArtifactValue>): string[] {
  return ids.filter(id => !videos.has(id)).map(id => `video not returned: ${id}`);
}

function readString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function readStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0) : [];
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? value as Record<string, unknown> : {};
}

function isListLikeTitle(title: string): boolean {
  return /\b(\d+\s+|top\s+\d+|list of|papers|tools|resources|chapters|lessons)\b/i.test(title);
}

async function runYtDlpJson(executable: string, args: string[], context: ExtractionAdapterContext): Promise<unknown> {
  assertNoMediaDownloadArgs(args);
  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, {
      shell: false,
      windowsHide: true,
      signal: context.signal,
      cwd: context.scratchDirectory,
    });
    const timeout = setTimeout(() => {
      child.kill('SIGTERM');
      reject(new Error('yt-dlp timed out'));
    }, context.timeoutMs);
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', chunk => { stdout += chunk; });
    child.stderr.on('data', chunk => { stderr += chunk; });
    child.on('error', error => {
      clearTimeout(timeout);
      reject(error);
    });
    child.on('close', code => {
      clearTimeout(timeout);
      if (code !== 0) {
        reject(new Error(stderr.trim() || `yt-dlp exited with ${code}`));
        return;
      }
      try {
        resolve(JSON.parse(stdout));
      } catch (error) {
        reject(error);
      }
    });
  });
}
