import { z } from 'zod';

export const YouTubeTranscriptStatus = z.enum([
  'not_attempted',
  'available_artifact',
  'blocked_auth_required',
  'not_available',
  'adapter_disabled',
  'adapter_failed',
]);
export type YouTubeTranscriptStatus = z.infer<typeof YouTubeTranscriptStatus>;

export const YouTubeTranscriptProvenance = z.enum([
  'official_owner_api',
  'optional_local_ytdlp',
  'manual_paste',
  'none',
]);

export const YouTubeTranscriptSegment = z.object({
  startSeconds: z.number().min(0),
  durationSeconds: z.number().min(0).optional(),
  text: z.string().min(1),
});

export const YouTubeTranscriptArtifact = z.object({
  status: YouTubeTranscriptStatus,
  provenance: YouTubeTranscriptProvenance,
  language: z.string().optional(),
  isAutoGenerated: z.boolean().optional(),
  segments: z.array(YouTubeTranscriptSegment).default([]),
  plainText: z.string().optional(),
  failureReason: z.string().optional(),
});
export type YouTubeTranscriptArtifact = z.infer<typeof YouTubeTranscriptArtifact>;

export const YouTubeChapter = z.object({
  title: z.string(),
  startSeconds: z.number().min(0),
});

export const YouTubeMetadataArtifact = z.object({
  videoId: z.string(),
  playlistId: z.string().optional(),
  canonicalUrl: z.string().url(),
  title: z.string().optional(),
  channelId: z.string().optional(),
  channelTitle: z.string().optional(),
  descriptionText: z.string().optional(),
  durationSeconds: z.number().min(0).optional(),
  publishedAt: z.string().optional(),
  thumbnailUrl: z.string().url().optional(),
  tags: z.array(z.string()).default([]),
  chapters: z.array(YouTubeChapter).default([]),
  linksMentioned: z.array(z.string().url()).default([]),
  transcript: YouTubeTranscriptArtifact,
  extractionQuality: z.enum([
    'url_only',
    'metadata_only',
    'description',
    'transcript_partial',
    'transcript_full',
  ]),
});
export type YouTubeMetadataArtifact = z.infer<typeof YouTubeMetadataArtifact>;

export const YouTubeAdapterPolicy = z.object({
  officialDataApi: z.object({
    enabled: z.boolean().default(false),
    apiKeyEnvironmentVariable: z.string().default('YOUTUBE_API_KEY'),
  }).default({ enabled: false, apiKeyEnvironmentVariable: 'YOUTUBE_API_KEY' }),
  localYtDlp: z.object({
    enabled: z.boolean().default(false),
    executable: z.string().default('yt-dlp'),
    allowAutomaticCaptions: z.boolean().default(false),
    preferredLanguages: z.array(z.string()).default(['en.*']),
  }).default({ enabled: false, executable: 'yt-dlp', allowAutomaticCaptions: false, preferredLanguages: ['en.*'] }),
  manualPaste: z.object({ enabled: z.boolean().default(true) }).default({ enabled: true }),
});
export type YouTubeAdapterPolicy = z.infer<typeof YouTubeAdapterPolicy>;

export function deriveYouTubeQuality(
  metadata: Pick<YouTubeMetadataArtifact, 'descriptionText' | 'transcript'>,
): YouTubeMetadataArtifact['extractionQuality'] {
  if (metadata.transcript.status === 'available_artifact') {
    return metadata.transcript.segments.length > 0 ? 'transcript_full' : 'transcript_partial';
  }
  if (metadata.descriptionText?.trim()) return 'description';
  return 'metadata_only';
}
